DROP TABLE IF EXISTS "bureau";
DROP TABLE IF EXISTS "bureau_balance";
DROP TABLE IF EXISTS "credit_card_balance";
DROP TABLE IF EXISTS "installments_payments";
DROP TABLE IF EXISTS "pOS_CASH_balance";
DROP TABLE IF EXISTS "previous_application";
DROP TABLE IF EXISTS "Application_train";

CREATE TABLE "bureau" (
    "SK_ID_CURR" BIGINT   NOT NULL,
    "SK_ID_BUREAU" BIGINT   NOT NULL,
    "CREDIT_ACTIVE" varchar   NOT NULL,
    "CREDIT_CURRENCY" varchar   NOT NULL,
    "DAYS_CREDIT" int   NOT NULL,
    "CREDIT_DAY_OVERDUE" int   NOT NULL,
    "DAYS_CREDIT_ENDDATE" float   NOT NULL,
    "DAYS_ENDDATE_FACT" float   NOT NULL,
    "AMT_CREDIT_MAX_OVERDUE" float   NOT NULL,
    "CNT_CREDIT_PROLONG" int   NOT NULL,
    "AMT_CREDIT_SUM" float   NOT NULL,
    "AMT_CREDIT_SUM_DEBT" float   NOT NULL,
    "AMT_CREDIT_SUM_LIMIT" float   NOT NULL,
    "AMT_CREDIT_SUM_OVERDUE" float   NOT NULL,
    "CREDIT_TYPE" varchar   NOT NULL,
    "DAYS_CREDIT_UPDATE" int   NOT NULL,
    "AMT_ANNUITY" float   NOT NULL
);

CREATE TABLE "bureau_balance" (
    "SK_ID_BUREAU" BIGINT   NOT NULL,
    "MONTHS_BALANCE" BIGINT   NOT NULL,
    "STATUS" varchar   NOT NULL
);

CREATE TABLE "credit_card_balance" (
    "SK_ID_PREV" int   NOT NULL,
    "SK_ID_CURR" int   NOT NULL,
    "MONTHS_BALANCE" int   NOT NULL,
    "AMT_BALANCE" float   NOT NULL,
    "AMT_CREDIT_LIMIT_ACTUAL" int   NOT NULL,
    "AMT_DRAWINGS_ATM_CURRENT" float   NOT NULL,
    "AMT_DRAWINGS_CURRENT" float   NOT NULL,
    "AMT_DRAWINGS_OTHER_CURRENT" float   NOT NULL,
    "AMT_DRAWINGS_POS_CURRENT" float   NOT NULL,
    "AMT_INST_MIN_REGULARITY" float   NOT NULL,
    "AMT_PAYMENT_CURRENT" float   NOT NULL,
    "AMT_PAYMENT_TOTAL_CURRENT" float   NOT NULL,
    "AMT_RECEIVABLE_PRINCIPAL" float   NOT NULL,
    "AMT_RECIVABLE" float   NOT NULL,
    "AMT_TOTAL_RECEIVABLE" float   NOT NULL,
    "CNT_DRAWINGS_ATM_CURRENT" float   NOT NULL,
    "CNT_DRAWINGS_CURRENT" int   NOT NULL,
    "CNT_DRAWINGS_OTHER_CURRENT" float   NOT NULL,
    "CNT_DRAWINGS_POS_CURRENT" float   NOT NULL,
    "CNT_INSTALMENT_MATURE_CUM" float   NOT NULL,
    "NAME_CONTRACT_STATUS" varchar   NOT NULL,
    "SK_DPD" int   NOT NULL,
    "SK_DPD_DEF" int   NOT NULL
);

CREATE TABLE "installments_payments" (
    "SK_ID_PREV" int   NOT NULL,
    "SK_ID_CURR" int   NOT NULL,
    "NUM_INSTALMENT_VERSION" float   NOT NULL,
    "NUM_INSTALMENT_NUMBER" int   NOT NULL,
    "DAYS_INSTALMENT" float   NOT NULL,
    "DAYS_ENTRY_PAYMENT" float   NOT NULL,
    "AMT_INSTALMENT" float   NOT NULL,
    "AMT_PAYMENT" float   NOT NULL
);

CREATE TABLE "pOS_CASH_balance" (
    "SK_ID_PREV" int   NOT NULL,
    "SK_ID_CURR" int   NOT NULL,
    "MONTHS_BALANCE" int   NOT NULL,
    "CNT_INSTALMENT" float   NOT NULL,
    "CNT_INSTALMENT_FUTURE" float   NOT NULL,
    "NAME_CONTRACT_STATUS" varchar   NOT NULL,
    "SK_DPD" int   NOT NULL,
    "SK_DPD_DEF" int   NOT NULL
);

CREATE TABLE "previous_application" (
    "SK_ID_PREV" int   NOT NULL,
    "SK_ID_CURR" int   NOT NULL,
    "NAME_CONTRACT_TYPE" varchar   NOT NULL,
    "AMT_ANNUITY" float   NOT NULL,
    "AMT_APPLICATION" float   NOT NULL,
    "AMT_CREDIT" float   NOT NULL,
    "AMT_DOWN_PAYMENT" float   NOT NULL,
    "AMT_GOODS_PRICE" float   NOT NULL,
    "WEEKDAY_APPR_PROCESS_START" varchar   NOT NULL,
    "HOUR_APPR_PROCESS_START" INT   NOT NULL,
    "FLAG_LAST_APPL_PER_CONTRACT" varchar   NOT NULL,
    "NFLAG_LAST_APPL_IN_DAY" INT   NOT NULL,
    "RATE_DOWN_PAYMENT" float   NOT NULL,
    "RATE_INTEREST_PRIMARY" float   NOT NULL,
    "RATE_INTEREST_PRIVILEGED" float   NOT NULL,
    "NAME_CASH_LOAN_PURPOSE" varchar   NOT NULL,
    "NAME_CONTRACT_STATUS" varchar   NOT NULL,
    "DAYS_DECISION" INT   NOT NULL,
    "NAME_PAYMENT_TYPE" varchar   NOT NULL,
    "CODE_REJECT_REASON" varchar   NOT NULL,
    "NAME_TYPE_SUITE" varchar   NOT NULL,
    "NAME_CLIENT_TYPE" varchar   NOT NULL,
    "NAME_GOODS_CATEGORY" varchar   NOT NULL,
    "NAME_PORTFOLIO" varchar   NOT NULL,
    "NAME_PRODUCT_TYPE" varchar   NOT NULL,
    "CHANNEL_TYPE" varchar   NOT NULL,
    "SELLERPLACE_AREA" INT   NOT NULL,
    "NAME_SELLER_INDUSTRY" varchar   NOT NULL,
    "CNT_PAYMENT" float   NOT NULL,
    "NAME_YIELD_GROUP" varchar   NOT NULL,
    "PRODUCT_COMBINATION" varchar   NOT NULL,
    "DAYS_FIRST_DRAWING" float   NOT NULL,
    "DAYS_FIRST_DUE" float   NOT NULL,
    "DAYS_LAST_DUE_1ST_VERSION" float   NOT NULL,
    "DAYS_LAST_DUE" float   NOT NULL,
    "DAYS_TERMINATION" float   NOT NULL,
    "NFLAG_INSURED_ON_APPROVAL" float   NOT NULL
);
CREATE Table "Application_train"(

"SK_ID_CURR" int   NOT NULL,
"TARGET" int,
"NAME_CONTRACT_TYPE" varchar,
"CODE_GENDER" varchar,
"FLAG_OWN_CAR" boolean,
"FLAG_OWN_REALTY" boolean,
"CNT_CHILDREN" float,
"AMT_INCOME_TOTAL" float,
"AMT_CREDIT" float ,
"AMT_ANNUITY" float ,
"AMT_GOODS_PRICE" float ,
"NAME_INCOME_TYPE" varchar,
"NAME_EDUCATION_TYPE" varchar,
"NAME_FAMILY_STATUS" varchar,
"NAME_HOUSING_TYPE" varchar,
"DAYS_BIRTH" float,
"DAYS_EMPLOYED" float,
"DAYS_REGISTRATION" float,	
"DAYS_ID_PUBLISH" float,
"OWN_CAR_AGE" float ,
"FLAG_MOBIL" float ,
"FLAG_EMP_PHONE" float ,
"FLAG_WORK_PHONE" float ,
"FLAG_CONT_MOBILE" float ,
"FLAG_PHONE" float ,
"FLAG_EMAIL" float ,
"OCCUPATION_TYPE" varchar (50),
"CNT_FAM_MEMBERS" float,
"REGION_RATING_CLIENT" float,
"REGION_RATING_CLIENT_W_CITY" float,
"WEEKDAY_APPR_PROCESS_START" varchar,
"HOUR_APPR_PROCESS_START" float,
"REG_REGION_NOT_LIVE_REGION" float,
"REG_REGION_NOT_WORK_REGION" float,
"LIVE_REGION_NOT_WORK_REGION" float,
"REG_CITY_NOT_LIVE_CITY" float,
"REG_CITY_NOT_WORK_CITY" float,
"LIVE_CITY_NOT_WORK_CITY" float,
"ORGANIZATION_TYPE" varchar,
"OBS_30_CNT_SOCIAL_CIRCLE" float,
"DEF_30_CNT_SOCIAL_CIRCLE" float,
"OBS_60_CNT_SOCIAL_CIRCLE" float,
"DEF_60_CNT_SOCIAL_CIRCLE" float,
"DAYS_LAST_PHONE_CHANGE" float,
"AMT_REQ_CREDIT_BUREAU_HOUR" float,
"AMT_REQ_CREDIT_BUREAU_DAY" float,
"AMT_REQ_CREDIT_BUREAU_WEEK" float,	
"AMT_REQ_CREDIT_BUREAU_MON" float,
"AMT_REQ_CREDIT_BUREAU_QRT" float,
"AMT_REQ_CREDIT_BUREAU_YEAR" float

);