CREATE TABLE "Buraeu" (
  "SK_ID_CURR" int,
  "SK_ID_BUREAU" int PRIMARY KEY,
  "CREDIT_ACTIVE" varchar,
  "CREDIT_CURRENCY" varchar,
  "DAYS_CREDIT" int,
  "CREDIT_DAY_OVERDUE" int,
  "DAYS_CREDIT_ENDDATE" int,
  "DAYS_ENDDATE_FACT" int,
  "AMT_CREDIT_MAX_OVERDUE" int,
  "CNT_CREDIT_PROLONG" int,
  "AMT_CREDIT_SUM" int,
  "AMT_CREDIT_SUM_DEBT" int,
  "AMT_CREDIT_SUM_LIMIT" int,
  "AMT_CREDIT_SUM_OVERDUE" int,
  "CREDIT_TYPE" varchar,
  "DAYS_CREDIT_UPDATE" int,
  "AMT_ANNUITY" int
);

CREATE TABLE "Bureau_balance" (
  "SK_ID_BUREAU" int,
  "MONTHS_BALANCE" int,
  "STATUS" varchar
);

CREATE TABLE "credit_card_balance" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "MONTHS_BALANCE" int,
  "AMT_BALANCE" int,
  "AMT_CREDIT_LIMIT_ACTUAL" int,
  "AMT_DRAWINGS_ATM_CURRENT" int,
  "AMT_DRAWINGS_CURRENT" int,
  "AMT_DRAWINGS_OTHER_CURRENT" int,
  "AMT_DRAWINGS_POS_CURRENT" int,
  "AMT_INST_MIN_REGULARITY" int,
  "AMT_PAYMENT_CURRENT" int,
  "AMT_PAYMENT_TOTAL_CURRENT" int,
  "AMT_RECEIVABLE_PRINCIPAL" int,
  "AMT_RECIVABLE" int,
  "AMT_TOTAL_RECEIVABLE" int,
  "CNT_DRAWINGS_ATM_CURRENT" int,
  "CNT_DRAWINGS_CURRENT" int,
  "CNT_DRAWINGS_OTHER_CURRENT" int,
  "CNT_DRAWINGS_POS_CURRENT" int,
  "CNT_INSTALMENT_MATURE_CUM" int,
  "NAME_CONTRACT_STATUS" varchar,
  "SK_DPD" int,
  "SK_DPD_DEF" int,
  PRIMARY KEY ("SK_ID_PREV", "SK_ID_CURR")
);

CREATE TABLE "installments_payments" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "NUM_INSTALMENT_VERSION" int,
  "NUM_INSTALMENT_NUMBER" int,
  "DAYS_INSTALMENT" int,
  "DAYS_ENTRY_PAYMENT" int,
  "AMT_INSTALMENT" int,
  "AMT_PAYMENT" int,
  PRIMARY KEY ("SK_ID_PREV", "SK_ID_CURR")
);

CREATE TABLE "POS_CASH_balance" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "MONTHS_BALANCE" int,
  "CNT_INSTALMENT" int,
  "CNT_INSTALMENT_FUTURE" int,
  "NAME_CONTRACT_STATUS" varchar,
  "SK_DPD" int,
  "SK_DPD_DEF" int,
  PRIMARY KEY ("SK_ID_PREV", "SK_ID_CURR")
);

CREATE TABLE "previous_application" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "NAME_CONTRACT_TYPE" varchar,
  "AMT_ANNUITY" INT,
  "AMT_APPLICATION" INT,
  "AMT_CREDIT" INT,
  "AMT_DOWN_PAYMENT" INT,
  "AMT_GOODS_PRICE" INT,
  "WEEKDAY_APPR_PROCESS_START" varchar,
  "HOUR_APPR_PROCESS_START" INT,
  "FLAG_LAST_APPL_PER_CONTRACT" varchar,
  "NFLAG_LAST_APPL_IN_DAY" INT,
  "RATE_DOWN_PAYMENT" INT,
  "RATE_INTEREST_PRIMARY" INT,
  "RATE_INTEREST_PRIVILEGED" INT,
  "NAME_CASH_LOAN_PURPOSE" varchar,
  "NAME_CONTRACT_STATUS" varchar,
  "DAYS_DECISION" INT,
  "NAME_PAYMENT_TYPE" varchar,
  "CODE_REJECT_REASON" varchar,
  "NAME_TYPE_SUITE" varchar,
  "NAME_CLIENT_TYPE" varchar,
  "NAME_GOODS_CATEGORY" varchar,
  "NAME_PORTFOLIO" varchar,
  "NAME_PRODUCT_TYPE" varchar,
  "CHANNEL_TYPE" varchar,
  "SELLERPLACE_AREA" INT,
  "NAME_SELLER_INDUSTRY" varchar,
  "CNT_PAYMENT" INT,
  "NAME_YIELD_GROUP" varchar,
  "PRODUCT_COMBINATION" varchar,
  "DAYS_FIRST_DRAWING" INT,
  "DAYS_FIRST_DUE" INT,
  "DAYS_LAST_DUE_1ST_VERSION" INT,
  "DAYS_LAST_DUE" INT,
  "DAYS_TERMINATION" INT,
  "NFLAG_INSURED_ON_APPROVAL" INT,
  PRIMARY KEY ("SK_ID_PREV", "SK_ID_CURR")
);

ALTER TABLE "Bureau_balance" ADD FOREIGN KEY ("SK_ID_BUREAU") REFERENCES "Buraeu" ("SK_ID_BUREAU");
