
DROP TABLE IF EXISTS Bureau_balance;
DROP TABLE IF EXISTS Buraeu;
DROP TABLE IF EXISTS credit_card_balance;
DROP TABLE IF EXISTS installments_payments;
DROP TABLE IF EXISTS POS_CASH_balance;
DROP TABLE IF EXISTS previous_application;

CREATE TABLE "Buraeu" (
  "SK_ID_CURR" int,
  "SK_ID_BUREAU" int PRIMARY KEY,
  "CREDIT_ACTIVE" varchar,
  "CREDIT_CURRENCY" varchar,
  "DAYS_CREDIT" int,
  "CREDIT_DAY_OVERDUE" int,
  "DAYS_CREDIT_ENDDATE" float,
  "DAYS_ENDDATE_FACT" float,
  "AMT_CREDIT_MAX_OVERDUE" float,
  "CNT_CREDIT_PROLONG" int,
  "AMT_CREDIT_SUM" float,
  "AMT_CREDIT_SUM_DEBT" float,
  "AMT_CREDIT_SUM_LIMIT" float,
  "AMT_CREDIT_SUM_OVERDUE" float,
  "CREDIT_TYPE" varchar,
  "DAYS_CREDIT_UPDATE" int,
  "AMT_ANNUITY" float
);

CREATE TABLE "Bureau_balance" (
  "SK_ID_BUREAU" int,
  "MONTHS_BALANCE" int,
  "STATUS" varchar
);

CREATE TABLE "credit_card_balance" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "MONTHS_BALANCE" int,
  "AMT_BALANCE" float,
  "AMT_CREDIT_LIMIT_ACTUAL" int,
  "AMT_DRAWINGS_ATM_CURRENT" float,
  "AMT_DRAWINGS_CURRENT" float,
  "AMT_DRAWINGS_OTHER_CURRENT" float,
  "AMT_DRAWINGS_POS_CURRENT" float,
  "AMT_INST_MIN_REGULARITY" float,
  "AMT_PAYMENT_CURRENT" float,
  "AMT_PAYMENT_TOTAL_CURRENT" float,
  "AMT_RECEIVABLE_PRINCIPAL" float,
  "AMT_RECIVABLE" float,
  "AMT_TOTAL_RECEIVABLE" float,
  "CNT_DRAWINGS_ATM_CURRENT" float,
  "CNT_DRAWINGS_CURRENT" int,
  "CNT_DRAWINGS_OTHER_CURRENT" float,
  "CNT_DRAWINGS_POS_CURRENT" float,
  "CNT_INSTALMENT_MATURE_CUM" float,
  "NAME_CONTRACT_STATUS" varchar,
  "SK_DPD" int,
  "SK_DPD_DEF" int
  
);

CREATE TABLE "installments_payments" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "NUM_INSTALMENT_VERSION" float,
  "NUM_INSTALMENT_NUMBER" int,
  "DAYS_INSTALMENT" float,
  "DAYS_ENTRY_PAYMENT" float,
  "AMT_INSTALMENT" float,
  "AMT_PAYMENT" float
);

CREATE TABLE "POS_CASH_balance" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "MONTHS_BALANCE" int,
  "CNT_INSTALMENT" float,
  "CNT_INSTALMENT_FUTURE" float,
  "NAME_CONTRACT_STATUS" varchar,
  "SK_DPD" int,
  "SK_DPD_DEF" int 
);

CREATE TABLE "previous_application" (
  "SK_ID_PREV" int,
  "SK_ID_CURR" int,
  "NAME_CONTRACT_TYPE" varchar,
  "AMT_ANNUITY" float,
  "AMT_APPLICATION" float,
  "AMT_CREDIT" float,
  "AMT_DOWN_PAYMENT" float,
  "AMT_GOODS_PRICE" float,
  "WEEKDAY_APPR_PROCESS_START" varchar,
  "HOUR_APPR_PROCESS_START" INT,
  "FLAG_LAST_APPL_PER_CONTRACT" varchar,
  "NFLAG_LAST_APPL_IN_DAY" INT,
  "RATE_DOWN_PAYMENT" float,
  "RATE_INTEREST_PRIMARY" float,
  "RATE_INTEREST_PRIVILEGED" float,
  "NAME_CASH_LOAN_PURPOSE" varchar,
  "NAME_CONTRACT_STATUS" varchar,
  "DAYS_DECISION" INT,
  "NAME_PAYMENT_TYPE" varchar,
  "CODE_REJECT_REASON" varchar,
  "NAME_TYPE_SUITE" varchar,
  "NAME_CLIENT_TYPE" varchar,
  "NAME_GOODS_CATEGORY" varchar,
  "NAME_PORTFOLIO" varchar,
  "NAME_PRODUCT_TYPE" varchar,
  "CHANNEL_TYPE" varchar,
  "SELLERPLACE_AREA" INT,
  "NAME_SELLER_INDUSTRY" varchar,
  "CNT_PAYMENT" float,
  "NAME_YIELD_GROUP" varchar,
  "PRODUCT_COMBINATION" varchar,
  "DAYS_FIRST_DRAWING" float,
  "DAYS_FIRST_DUE" float,
  "DAYS_LAST_DUE_1ST_VERSION" float,
  "DAYS_LAST_DUE" float,
  "DAYS_TERMINATION" float,
  "NFLAG_INSURED_ON_APPROVAL" float
  
);

